import 'package:hive_ce/hive.dart';
import 'release_file.dart';
import 'todo_item.dart';

part 'release.g.dart'; // This will be generated by build_runner

@HiveType(typeId: 3)
class Release {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String title;

  @HiveField(2)
  final DateTime? releaseDate;

  @HiveField(3)
  final String? artworkImagePath;

  @HiveField(4)
  final String? description;

  @HiveField(5)
  final List<String> trackIds; // List of MusicProject IDs

  @HiveField(6)
  final List<ReleaseFile> files; // List of supporting files

  @HiveField(7)
  final List<TodoItem> todos; // TODO list for the release

  Release({
    required this.id,
    required this.title,
    this.releaseDate,
    this.artworkImagePath,
    this.description,
    required this.trackIds,
    this.files = const [],
    this.todos = const [],
  });

  Release copyWith({
    String? id,
    String? title,
    DateTime? releaseDate,
    String? artworkImagePath,
    String? description,
    List<String>? trackIds,
    List<ReleaseFile>? files,
    List<TodoItem>? todos,
    bool clearReleaseDate = false,
    bool clearArtworkImagePath = false,
    bool clearDescription = false,
  }) {
    return Release(
      id: id ?? this.id,
      title: title ?? this.title,
      releaseDate: clearReleaseDate ? null : (releaseDate ?? this.releaseDate),
      artworkImagePath: clearArtworkImagePath ? null : (artworkImagePath ?? this.artworkImagePath),
      description: clearDescription ? null : (description ?? this.description),
      trackIds: trackIds ?? this.trackIds,
      files: files ?? this.files,
      todos: todos ?? this.todos,
    );
  }
}

/// Every [MusicProject] id referenced by any release in [releases].
///
/// These projects are treated as protected throughout the app — removeRoot,
/// ignoring a path (`_deleteProjectsUnderPathPrefix`), and clearing all data
/// all skip them, and the dashboard's own project filter keeps showing them
/// even once their scan root is gone — because losing one would silently
/// drop a track from someone's release.
Set<String> releaseProtectedProjectIds(Iterable<Release> releases) {
  final ids = <String>{};
  for (final release in releases) {
    ids.addAll(release.trackIds);
  }
  return ids;
}
