// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:daw_project_manager/models/ignored_path.dart';
import 'package:daw_project_manager/models/music_project.dart';
import 'package:daw_project_manager/models/notification_preferences.dart';
import 'package:daw_project_manager/models/playlist.dart';
import 'package:daw_project_manager/models/profile.dart';
import 'package:daw_project_manager/models/project_event.dart';
import 'package:daw_project_manager/models/project_template.dart';
import 'package:daw_project_manager/models/release.dart';
import 'package:daw_project_manager/models/release_file.dart';
import 'package:daw_project_manager/models/scan_root.dart';
import 'package:daw_project_manager/models/template_root.dart';
import 'package:daw_project_manager/models/todo_item.dart';
import 'package:daw_project_manager/models/todo_template.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(IgnoredPathAdapter());
    registerAdapter(MusicProjectAdapter());
    registerAdapter(NotificationPreferencesAdapter());
    registerAdapter(PlaylistAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(ProjectEventAdapter());
    registerAdapter(ProjectTemplateAdapter());
    registerAdapter(ReleaseAdapter());
    registerAdapter(ReleaseFileAdapter());
    registerAdapter(ScanRootAdapter());
    registerAdapter(TemplateRootAdapter());
    registerAdapter(TodoItemAdapter());
    registerAdapter(TodoTemplateAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(IgnoredPathAdapter());
    registerAdapter(MusicProjectAdapter());
    registerAdapter(NotificationPreferencesAdapter());
    registerAdapter(PlaylistAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(ProjectEventAdapter());
    registerAdapter(ProjectTemplateAdapter());
    registerAdapter(ReleaseAdapter());
    registerAdapter(ReleaseFileAdapter());
    registerAdapter(ScanRootAdapter());
    registerAdapter(TemplateRootAdapter());
    registerAdapter(TodoItemAdapter());
    registerAdapter(TodoTemplateAdapter());
  }
}
